PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX fd: <http://fishdelish.cs.man.ac.uk/rdf/vocab/resource/>

SELECT * WHERE {
   ?x fd:collaborators_Personnel "333"^^xsd:int .
   OPTIONAL {?x fd:collaborators_Prename ?prename }.
   OPTIONAL {?x fd:collaborators_Surname ?surname }.
}